import type {
  Org,
  User,
  Persona,
  Evidence,
  Epoch,
  Account,
  Reference,
  Content,
  Lead,
  InboxItem,
  AppState,
  TeamMember,
  Settings,
} from "./types"

// Mock Organizations
export const mockOrgs: Org[] = [
  {
    id: "org-1",
    name: "智创科技",
    industry: "科技",
    city: "北京",
    isSensitive: false,
    logo: "/tech-company-logo.jpg",
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "org-2",
    name: "灵感工作室",
    industry: "教育培训",
    city: "上海",
    isSensitive: false,
    logo: "/creative-studio-logo.png",
    createdAt: "2024-03-15T00:00:00Z",
  },
]

// Mock Users
export const mockUsers: User[] = [
  {
    id: "user-1",
    name: "张三",
    email: "zhangsan@example.com",
    avatar: "/male-avatar.png",
    orgIds: ["org-1", "org-2"],
    role: "admin",
  },
]

// Mock Personas (IPs)
export const mockPersonas: Persona[] = [
  {
    id: "ip-1",
    orgId: "org-1",
    name: "科技老王",
    avatar: "/tech-blogger-avatar.jpg",
    bio: "专注于科技产品评测与行业趋势分析，帮助用户做出明智的购买决策。",
    type: "expert",
    status: "active",
    currentEpochId: "epoch-1",
    brandBook: {
      tone: "专业、亲和、务实",
      keywords: ["科技", "评测", "性价比", "新品"],
      avoidWords: ["绝对", "最好", "必买"],
      targetAudience: "25-45岁科技爱好者",
      valueProposition: "用专业视角解读科技，让选择更简单",
      communicationStyle: "数据说话，案例为证",
      contentPillars: ["产品评测", "行业观察", "选购指南"],
      visualIdentity: "科技蓝为主色，简洁现代风格",
    },
    offers: [
      {
        id: "offer-1",
        name: "产品评测合作",
        description: "深度体验+视频评测",
        price: 5000,
        benefits: ["专业深度评测", "全平台分发", "粉丝真实反馈"],
      },
      {
        id: "offer-2",
        name: "品牌咨询",
        description: "科技品牌营销策略咨询",
        price: 10000,
        benefits: ["1v1深度沟通", "定制化方案", "持续跟进"],
      },
    ],
    createdAt: "2024-01-15T00:00:00Z",
    updatedAt: "2024-12-01T00:00:00Z",
  },
  {
    id: "ip-2",
    orgId: "org-1",
    name: "职场小李",
    avatar: "/business-woman-avatar.png",
    bio: "分享职场成长心得，帮助职场新人快速提升。",
    type: "kol",
    status: "active",
    currentEpochId: "epoch-2",
    brandBook: {
      tone: "励志、实用、温暖",
      keywords: ["职场", "成长", "效率", "沟通"],
      avoidWords: ["躺平", "摆烂"],
      targetAudience: "22-35岁职场人士",
      valueProposition: "陪你一起职场进阶",
      communicationStyle: "故事化表达，真诚分享",
      contentPillars: ["职场技能", "向上管理", "人际关系"],
    },
    offers: [
      {
        id: "offer-3",
        name: "职场咨询",
        description: "1v1职业规划咨询",
        price: 500,
        benefits: ["简历诊断", "面试辅导", "职业规划"],
      },
    ],
    createdAt: "2024-06-01T00:00:00Z",
    updatedAt: "2024-11-20T00:00:00Z",
  },
]

// Mock Evidences
export const mockEvidences: Evidence[] = [
  {
    id: "ev-1",
    personaId: "ip-1",
    type: "case",
    title: "小米15系列首发评测播放量破百万",
    description: "该评测视频在发布首周获得120万播放量，带动相关产品销量增长15%",
    source: "抖音数据统计",
    date: "2024-11-01",
    tags: ["爆款", "手机", "小米"],
    scope: "public",
    createdAt: "2024-11-05T00:00:00Z",
  },
  {
    id: "ev-2",
    personaId: "ip-1",
    type: "testimonial",
    title: "某品牌方反馈",
    description: '"合作非常愉快，内容专业度高，粉丝互动积极"',
    source: "品牌方邮件",
    date: "2024-10-15",
    tags: ["合作反馈", "好评"],
    scope: "public",
    createdAt: "2024-10-16T00:00:00Z",
  },
  {
    id: "ev-3",
    personaId: "ip-1",
    type: "data",
    title: "2024年度数据总结",
    description: "全年发布内容156条，总播放量2300万，涨粉18万",
    date: "2024-12-01",
    tags: ["年度总结", "数据"],
    scope: "public",
    createdAt: "2024-12-01T00:00:00Z",
  },
  {
    id: "ev-4",
    personaId: "ip-2",
    type: "award",
    title: "小红书职场优质创作者认证",
    description: "获得小红书官方职场领域优质创作者认证",
    source: "小红书官方",
    date: "2024-09-01",
    tags: ["认证", "荣誉"],
    scope: "public",
    createdAt: "2024-09-02T00:00:00Z",
  },
]

// Mock Epochs
export const mockEpochs: Epoch[] = [
  {
    id: "epoch-1",
    personaId: "ip-1",
    name: "2024Q4冲刺期",
    startDate: "2024-10-01",
    endDate: "2024-12-31",
    description: "年末冲刺，聚焦新品评测和年度盘点",
    goals: ["完成20条深度评测", "涨粉5万", "签约3个品牌合作"],
    priorityTopics: ["年度盘点", "新品首发", "选购指南"],
    platformWeights: { douyin: 50, xiaohongshu: 30, wechat: 20 },
    isCurrent: true,
    createdAt: "2024-10-01T00:00:00Z",
  },
  {
    id: "epoch-2",
    personaId: "ip-2",
    name: "年终晋升季",
    startDate: "2024-11-01",
    endDate: "2025-01-31",
    description: "聚焦年终述职和晋升准备",
    goals: ["产出30条高质量内容", "咨询转化10单"],
    priorityTopics: ["年终述职", "晋升谈判", "向上管理"],
    platformWeights: { douyin: 20, xiaohongshu: 60, wechat: 20 },
    isCurrent: true,
    createdAt: "2024-11-01T00:00:00Z",
  },
]

// Mock Accounts
export const mockAccounts: Account[] = [
  {
    id: "acc-1",
    personaId: "ip-1",
    platform: "douyin",
    accountId: "techlaowang",
    accountName: "科技老王",
    followers: 580000,
    isVerified: true,
    status: "active",
    createdAt: "2023-01-01T00:00:00Z",
  },
  {
    id: "acc-2",
    personaId: "ip-1",
    platform: "xiaohongshu",
    accountId: "techlaowang_xhs",
    accountName: "科技老王",
    followers: 120000,
    isVerified: true,
    status: "active",
    createdAt: "2023-06-01T00:00:00Z",
  },
  {
    id: "acc-3",
    personaId: "ip-1",
    platform: "wechat",
    accountId: "techlaowang_wx",
    accountName: "科技老王说",
    followers: 45000,
    isVerified: false,
    status: "active",
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "acc-4",
    personaId: "ip-2",
    platform: "xiaohongshu",
    accountId: "careerxiaoli",
    accountName: "职场小李",
    followers: 85000,
    isVerified: true,
    status: "active",
    createdAt: "2024-06-01T00:00:00Z",
  },
]

// Mock References
export const mockReferences: Reference[] = [
  {
    id: "ref-1",
    personaId: "ip-1",
    type: "article",
    title: "2024年智能手机市场趋势分析",
    url: "https://example.com/article1",
    platform: "wechat",
    summary: "文章分析了2024年智能手机市场的主要趋势，包括AI功能普及、折叠屏增长等",
    tags: ["行业分析", "手机", "AI"],
    source: "36氪",
    extracted: {
      hook: "2024年手机行业最大变化：AI不再是噱头",
      structure: "现状-问题-趋势-建议",
      highlights: ["数据详实", "观点新颖"],
      risks: ["篇幅较长"],
    },
    isInspiration: true,
    collectedAt: "2024-12-01T00:00:00Z",
  },
  {
    id: "ref-2",
    personaId: "ip-1",
    type: "video",
    title: "竞品账号爆款视频分析",
    url: "https://example.com/video1",
    platform: "douyin",
    summary: "分析了某竞品账号的爆款视频结构：强hook+痛点展示+解决方案+CTA",
    tags: ["竞品分析", "爆款", "视频结构"],
    source: "抖音",
    extracted: {
      hook: "花了5000块买了这些垃圾...",
      structure: "痛点-踩坑-解决方案",
      cta: "关注避坑",
      format: "talking-head",
      highlights: ["情绪共鸣强", "节奏快"],
    },
    isInspiration: false,
    collectedAt: "2024-11-28T00:00:00Z",
  },
  {
    id: "ref-3",
    personaId: "ip-2",
    type: "post",
    title: "职场沟通技巧热门笔记",
    url: "https://example.com/post1",
    platform: "xiaohongshu",
    summary: "一篇关于职场向上沟通的热门笔记，互动率很高",
    tags: ["职场沟通", "热门", "参考"],
    source: "小红书",
    extracted: {
      hook: "领导最讨厌的5种汇报方式",
      structure: "问题清单-解决方案-总结",
      format: "listicle",
    },
    collectedAt: "2024-12-05T00:00:00Z",
  },
]

// Mock Contents
export const mockContents: Content[] = [
  {
    id: "DY-2024W49-001",
    personaId: "ip-1",
    accountId: "acc-1",
    platform: "douyin",
    title: "小米15 Pro深度体验：这次真的能打了？",
    topicCluster: "产品评测",
    format: "talking-head",
    epochId: "epoch-1",
    script: {
      hook: "花了一周时间深度体验小米15 Pro，发现了几个官方没告诉你的细节",
      outline: ["外观设计变化", "性能实测", "影像系统", "续航充电", "总结推荐"],
      fullScript: "大家好，我是科技老王。今天这期视频，我花了整整一周时间，深度体验了小米15 Pro...",
      shootingNotes: ["需要准备小米15 Pro和竞品对比", "准备充电速度测试设备"],
    },
    evidenceIds: ["ev-1"],
    referenceIds: ["ref-1"],
    status: "published",
    qaResult: {
      verdict: "pass",
      score: 92,
      issues: [],
      suggestions: ["可以增加与上一代的对比"],
      checkedAt: "2024-12-01T08:00:00Z",
    },
    publishPack: {
      titleCandidates: [
        "小米15 Pro深度体验：这次真的能打了？",
        "用了一周小米15 Pro，说几个真实感受",
        "小米15 Pro值不值得买？深度评测告诉你",
      ],
      caption:
        "花了一周时间深度体验小米15 Pro，给大家分享几个官方没告诉你的细节。从外观到性能，从影像到续航，全方位测评来了！",
      hashtags: ["#小米15Pro", "#手机评测", "#科技数码", "#小米"],
      coverText: "小米15 Pro | 深度评测",
      pinnedComment: "你们最关心小米15 Pro哪个方面？评论区告诉我",
      abTestSuggestion: "封面可以测试：产品图 vs 真人举机",
      generatedAt: "2024-12-01T09:00:00Z",
    },
    publishedAt: "2024-12-02T10:00:00Z",
    publishUrl: "https://douyin.com/video/123456",
    metrics: {
      views: 156000,
      likes: 8900,
      comments: 1200,
      shares: 890,
      inquiries: 12,
      appointments: 3,
      deals: 1,
      updatedAt: "2024-12-10T00:00:00Z",
    },
    weekNumber: "2024W49",
    createdAt: "2024-11-30T00:00:00Z",
    updatedAt: "2024-12-10T00:00:00Z",
  },
  {
    id: "XHS-2024W49-001",
    personaId: "ip-1",
    accountId: "acc-2",
    platform: "xiaohongshu",
    title: "2024年最值得买的5款耳机推荐",
    topicCluster: "选购指南",
    format: "listicle",
    epochId: "epoch-1",
    script: {
      hook: "入坑耳机3年，这5款是我心中的年度之选",
      outline: ["索尼WH-1000XM5", "AirPods Pro 2", "森海塞尔Momentum 4", "Bose QC45", "华为FreeBuds Pro 3"],
    },
    evidenceIds: [],
    referenceIds: [],
    status: "qa_fix",
    qaResult: {
      verdict: "fix",
      score: 68,
      issues: ["缺少证据支撑", "标题含有绝对化用语"],
      suggestions: ["补充个人使用数据", "修改标题为更客观的表述"],
      checkedAt: "2024-12-05T10:00:00Z",
    },
    weekNumber: "2024W49",
    createdAt: "2024-12-05T00:00:00Z",
    updatedAt: "2024-12-05T00:00:00Z",
  },
  {
    id: "WX-2024W50-001",
    personaId: "ip-1",
    accountId: "acc-3",
    platform: "wechat",
    title: "年终盘点：2024年科技圈十大事件",
    topicCluster: "年度盘点",
    format: "listicle",
    epochId: "epoch-1",
    script: {
      hook: "2024年科技圈发生了太多大事，我挑了10件最值得聊的",
      outline: [],
    },
    evidenceIds: ["ev-3"],
    referenceIds: ["ref-1"],
    status: "draft",
    weekNumber: "2024W50",
    createdAt: "2024-12-10T00:00:00Z",
    updatedAt: "2024-12-10T00:00:00Z",
  },
  {
    id: "DY-2024W50-001",
    personaId: "ip-1",
    accountId: "acc-1",
    platform: "douyin",
    title: "iPhone 17概念设计曝光",
    topicCluster: "行业观察",
    status: "idea",
    evidenceIds: [],
    referenceIds: [],
    weekNumber: "2024W50",
    createdAt: "2024-12-11T00:00:00Z",
    updatedAt: "2024-12-11T00:00:00Z",
  },
  {
    id: "XHS-2024W50-001",
    personaId: "ip-2",
    accountId: "acc-4",
    platform: "xiaohongshu",
    title: "职场新人必看：和领导沟通的3个技巧",
    topicCluster: "向上管理",
    format: "listicle",
    epochId: "epoch-2",
    script: {
      hook: "学会这3招，让领导对你刮目相看",
      outline: ["主动汇报进度", "带着方案提问题", "学会向上管理预期"],
      fullScript: "入职3年，总结出这几条和领导沟通的经验...",
    },
    evidenceIds: ["ev-4"],
    referenceIds: ["ref-3"],
    status: "approved",
    qaResult: {
      verdict: "pass",
      score: 88,
      issues: [],
      suggestions: ["可以加入更多具体案例"],
      checkedAt: "2024-12-12T08:00:00Z",
    },
    scheduledAt: "2024-12-15T10:00:00Z",
    weekNumber: "2024W50",
    createdAt: "2024-12-08T00:00:00Z",
    updatedAt: "2024-12-12T00:00:00Z",
  },
  {
    id: "XHS-2024W48-001",
    personaId: "ip-2",
    accountId: "acc-4",
    platform: "xiaohongshu",
    title: "年底了，怎么和老板谈加薪？",
    topicCluster: "晋升谈判",
    format: "story",
    epochId: "epoch-2",
    script: {
      hook: "年底述职季，很多人问我怎么开口谈加薪",
    },
    evidenceIds: [],
    referenceIds: [],
    status: "published",
    publishedAt: "2024-11-28T10:00:00Z",
    publishUrl: "https://xiaohongshu.com/note/789",
    metrics: {
      views: 89000,
      likes: 5600,
      comments: 890,
      saves: 3200,
      inquiries: 8,
      appointments: 2,
      updatedAt: "2024-12-10T00:00:00Z",
    },
    weekNumber: "2024W48",
    createdAt: "2024-11-25T00:00:00Z",
    updatedAt: "2024-12-10T00:00:00Z",
  },
]

// Mock Leads
export const mockLeads: Lead[] = [
  {
    id: "lead-1",
    personaId: "ip-1",
    name: "某手机品牌市场部",
    contact: "marketing@brand.com",
    platform: "微信",
    source: "dm",
    sourceContentId: "DY-2024W49-001",
    status: "qualified",
    leadLevel: "hot",
    needTag: "品牌合作",
    nextAction: "下周一电话沟通合作细节",
    notes: "希望合作新品发布评测，预算5-8万",
    tags: ["品牌合作", "高预算"],
    createdAt: "2024-12-05T00:00:00Z",
    updatedAt: "2024-12-08T00:00:00Z",
  },
  {
    id: "lead-2",
    personaId: "ip-1",
    name: "数码配件厂商",
    contact: "bd@accessories.com",
    source: "comment",
    status: "contacted",
    leadLevel: "warm",
    nextAction: "等待对方回复报价需求",
    notes: "在评论区询问合作，已回复私信",
    tags: ["配件", "待跟进"],
    createdAt: "2024-12-10T00:00:00Z",
    updatedAt: "2024-12-10T00:00:00Z",
  },
  {
    id: "lead-3",
    personaId: "ip-2",
    name: "职场培训机构",
    contact: "13800138000",
    platform: "小红书",
    source: "dm",
    status: "new",
    leadLevel: "warm",
    needTag: "课程推广",
    notes: "希望合作职场课程推广",
    tags: ["课程推广"],
    createdAt: "2024-12-12T00:00:00Z",
    updatedAt: "2024-12-12T00:00:00Z",
  },
]

// Mock Inbox Items
export const mockInboxItems: InboxItem[] = [
  {
    id: "inbox-1",
    personaId: "ip-1",
    type: "voice",
    title: "关于折叠屏选题的思考",
    transcript:
      "今天突然想到一个选题，关于折叠屏手机的真实使用场景，不要再聊参数了，用户真正关心的是能不能用、好不好用。可以做一期一周体验vlog，记录真实使用中的优缺点...",
    memoSummary: "折叠屏选题灵感：聚焦真实使用场景而非参数对比，可做一周体验vlog",
    duration: 180,
    status: "processed",
    extractedAssets: {
      topicSeeds: ["折叠屏真实使用场景盘点", "折叠屏一周体验vlog", "折叠屏值不值得买"],
      evidenceClues: ["需要借用多款折叠屏手机做对比"],
      strategySignals: ["用户对参数对比已审美疲劳，需要转向实用内容"],
    },
    createdAt: "2024-12-10T08:30:00Z",
  },
  {
    id: "inbox-2",
    personaId: "ip-1",
    type: "voice",
    title: "新录音",
    duration: 45,
    status: "pending",
    createdAt: "2024-12-12T14:20:00Z",
  },
  {
    id: "inbox-3",
    personaId: "ip-2",
    type: "text",
    title: "粉丝私信整理",
    transcript: "最近收到很多粉丝私信问职场焦虑怎么办，可以做一期内容专门聊这个话题",
    memoSummary: "职场焦虑话题需求旺盛，可做专题内容",
    status: "processed",
    extractedAssets: {
      topicSeeds: ["职场焦虑怎么办", "35岁危机真的存在吗"],
      objections: ["怕被认为贩卖焦虑"],
    },
    createdAt: "2024-12-11T16:00:00Z",
  },
]

// Mock Team Members
export const mockTeamMembers: TeamMember[] = [
  {
    id: "tm-1",
    orgId: "org-1",
    name: "张三",
    email: "zhangsan@example.com",
    role: "admin",
    invitedAt: "2024-01-01T00:00:00Z",
    status: "active",
  },
  {
    id: "tm-2",
    orgId: "org-1",
    name: "李四",
    email: "lisi@example.com",
    role: "editor",
    invitedAt: "2024-06-01T00:00:00Z",
    status: "active",
  },
]

// Mock Settings
export const mockSettings: Settings[] = [
  {
    orgId: "org-1",
    bannedWords: ["绝对", "最好", "必买", "保证", "100%"],
    defaultWeeklyRatio: { douyin: 6, xiaohongshu: 4, wechat: 2 },
    defaultFormats: ["talking-head", "listicle", "tutorial"],
  },
]

// 空白初始状态 - 新用户从这里开始
export const emptyAppState: AppState = {
  currentOrgId: null,
  currentIpId: null,
  isAuthenticated: false,
  currentUser: null,
  orgs: [],
  users: [],
  personas: [],
  epochs: [],
  evidences: [],
  accounts: [],
  references: [],
  contents: [],
  leads: [],
  inboxItems: [],
  weeklyReports: [],
  teamMembers: [],
  settings: [],
  weeklyDraftSources: [],
  assistantStage: "not_started",
}

// Mock 初始状态 - 仅用于开发演示
export const mockAppState: AppState = {
  currentOrgId: null,
  currentIpId: null,
  isAuthenticated: false,
  currentUser: null,
  orgs: mockOrgs,
  users: mockUsers,
  personas: mockPersonas,
  epochs: mockEpochs,
  evidences: mockEvidences,
  accounts: mockAccounts,
  references: mockReferences,
  contents: mockContents,
  leads: mockLeads,
  inboxItems: mockInboxItems,
  weeklyReports: [],
  teamMembers: mockTeamMembers,
  settings: mockSettings,
  weeklyDraftSources: [],
  assistantStage: "not_started",
}

// 默认使用空白状态（新用户）
export const initialAppState = emptyAppState
